version: '3'

services:
  mongodb:
    image: mongo:3.4
    container_name: mongo
    volumes:
      - ./infra/mongo/:/data/db

  demo-user:
    image: mradul/demo-user
    container_name: demo-user
    ports:
        - 8012:8012