version: '3'

services:
  mongodb:
    image: mongo:3.4
    container_name: mongo
    volumes:
      - ./infra/mongo/:/data/db

  demo-user-service:
    image: jinternals/demo-user-service
    container_name: demo-user-service
    ports:
        - 8012:8012

  demo-user-v1-consumer:
    image: jinternals/demo-user-v1-consumer
    container_name: demo-user-v1-consumer
    ports:
        - 8013:8013

  demo-user-v2-consumer:
    image: jinternals/demo-user-v2-consumer
    container_name: demo-user-v2-consumer
    ports:
        - 8014:8014