version: '3'

services:
  mongodb:
    image: mongo:3.4
    container_name: mongo
    volumes:
      - ./infra/mongo/:/data/db

  docker-user:
    image: mradul/docker-user
    container_name: docker-user
    links:
       - mongodb
    ports:
        - 8012:8012