server:
  port: 8080

stubrunner:
  stubs-mode: local
  stream:
    enabled: false
  ids:
   - com.jinternals:demo-user-service:+:stubs:8081

spring:
  main:
    allow-bean-definition-overriding: true